services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlcontainer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=X7@pL9qW#zT2
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "14333:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - lancamentos-network
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lancamentos-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  controle-lancamentos-api:
    build:
      context: ./ControleDeLancamentos
      dockerfile: ./ControleDeLancamentos/Dockerfile
    container_name: controle-lancamentos-api
    ports:
    - "7105:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=sql-server;Database=ControleDeLancamentos;User Id=sa;Password=X7@pL9qW#zT2;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RABBIT_HOST_NAME=rabbitmq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_PORT=5672
      - RABBIT_LANCAMENTO_QUEUE=lancamentos
    depends_on:
      sql-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - lancamentos-network

  consolidado-diario-api:
    build:
      context: ./ConsolidadoDiario 
      dockerfile: ./ConsolidadoDiario/Dockerfile
    container_name: consolidado-diario-api
    ports:
      - "7106:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=sql-server;Database=ControleDeLancamentos;User Id=sa;Password=X7@pL9qW#zT2;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RABBIT_HOST_NAME=rabbitmq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_PORT=5672
      - RABBIT_LANCAMENTO_QUEUE=lancamentos
    depends_on:
      sql-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - lancamentos-network

  frontend:
    build:
      context: ./ControleDeLancamentos-front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./ControleDeLancamentos-front/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:

      - REACT_APP_API_LANCAMENTOS_URL=/api/lancamentos
      - REACT_APP_API_CONSOLIDADOS_URL=/api/consolidados
    depends_on:
      - controle-lancamentos-api
      - consolidado-diario-api
    networks:
      - lancamentos-network

  migrations:
    build:
      context: ./
      dockerfile: Dockerfile.migrations
    container_name: migrations-runner
    environment:
      - CONNECTION_STRING=Server=sql-server;Database=ControleDeLancamentos;User Id=sa;Password=X7@pL9qW#zT2;TrustServerCertificate=True;
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - lancamentos-network

networks:
  lancamentos-network:
    driver: bridge

volumes:
  sql-data:
    driver: local